### ISSUE TITLE
模板函数中无表达意义的下划线数组

### ISSUE THREAD

**Issue by MrShinshi** [Mq-b/Modern-Cpp-templates-tutorial#13]
如果这是你的个人 癖好请去掉,如果不是请解释不这样可能在哪些情形下导致什么后果.

**Comment by MrShinshi** [comment]
如果这是你的个人 癖好请去掉,如果不是请解释不这样可能在哪些情形下导致什么后果.

**Comment by Mq-b** [comment]
`_` 代表它毫无意义。

**Comment by MrShinshi** [comment]
`_` 可以代表毫无意义,但是
```cpp
int[]_{ ( do sth , ... ) }; 
```
这个写法必须是有意义的(比如"不这么写会导致某些编译器不进行展开"之类的理由), 不然我就想到new之后 == nullptr了

**Comment by Mq-b** [comment]
> `_` 可以代表毫无意义,但是
> 
> ```c++
> int[]_{ ( do sth , ... ) }; 
> ```
> 
> 这个写法必须是有意义的(比如"不这么写会导致某些编译器不进行展开"之类的理由), 不然我就想到new之后 == nullptr了

[原文](https://github.com/Mq-b/Modern-Cpp-templates-tutorial/blob/main/md/%E7%AC%AC%E4%B8%80%E9%83%A8%E5%88%86-%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86/01%E5%87%BD%E6%95%B0%E6%A8%A1%E6%9D%BF.md#%E5%8F%AF%E5%8F%98%E5%8F%82%E6%95%B0%E6%A8%A1%E6%9D%BF)：

> 很明显是为了打印，对，但是为啥要括号里加个逗号零呢？这是因为逗号表达式是从左往右执行的，返回最右边的值作为整个逗号表达式的值，也就是说：每一个 (std::cout << arg0 << ' ' ,0) 都会返回 0，**这主要是为了符合语法，让它能正常执行。我们创建了一个数组 int _[] ，最终这些 0 会用来初始化这个数组，当然，这个数组本身没有用，只是为了符合语法。**

**Comment by MrShinshi** [comment]
那为什么不采用如下写法
```cpp
template <typename...Args>
void print(Args&&...args)
{
    ((std::cout << args),...);
}
```

**Comment by Mq-b** [comment]
因为还没讲到折叠表达式

**Comment by Mq-b** [comment]
新老写法都要学学

**Comment by MrShinshi** [comment]
那就应该标注这个是老写法, 或者干脆使用新写法但告诉他们
> 这个写法需要C++xx之后才能使用, 老写法请参考 `折叠表达式` 专题.

**Comment by Mq-b** [comment]
在 Markdown 交流中 “>” 通常表示引用，补充等意思，你这语法一写出来我还是思考了一下。

尤其是这种对话 “>” 几乎只表示引用。

**Comment by MrShinshi** [comment]
酱紫,学习了

**Comment by Mq-b** [comment]
> 那就应该标注这个是老写法, 或者干脆使用新写法但告诉他们 :
> 
> "这个写法需要C++xx之后才能使用, 老写法请参考 `折叠表达式` 专题."

这几乎是不可行的，如果不准备在当前就讲新内容，而是直接说明这是老式写法，大大降低学习欲望，应当留到小节最后说明还会有新的写法进行形参包展开。

**Comment by Mq-b** [comment]
或者在开头表示“先不讲xxx“，但是这其实没用，这种话说出来就是给懂的人看的，不懂的人根本不知道也不需要看这句话。

**Comment by Mq-b** [comment]
只能bb一句：

> 本节先默认 C++14 标准

**Comment by Mq-b** [comment]
https://github.com/Mq-b/Modern-Cpp-templates-tutorial/commit/19c4e3c5da30a0a35b39d47c2a3a8574e36802b1

**Comment by MrShinshi** [comment]
那换个思路, 干脆把你那"魔法"出来的折叠表达式删掉, 提一句
> C++xx 之前是不支持 `折叠表达式` 的, 关于折叠表达式的部分请参考 `折叠表达式` 专题
至于读者怎么魔是读者的问题, 你直接带头魔却不准确的表达出来是不妥当的

**Comment by Mq-b** [comment]
没问题，我现在的表述非常好，不需要别的徒增烦恼

**Comment by MrShinshi** [comment]
看了下 commit, 还行
