### ISSUE TITLE
`requires` 表达式中“类型要求”

### ISSUE THREAD

**Issue by Mq-b** [Mq-b/Modern-Cpp-templates-tutorial#15]
众所周知，`requires` 表达式如果要使用类型要求，得在要求序列中写 `typename`，但是为何以下代码不需要，且结果正确，那它是什么？

```cpp
#include <iostream>

template<typename T>
void f(T){
    constexpr bool v = requires{ T::type; };
    std::cout << std::boolalpha << v << '\n';
}

struct X { using type = void; };

int main(){
    f(1);   // false 因为 int::type 不是合法表达式
    f(X{}); // true 因为 X::type 是合法表达式
}
```

[测试](https://godbolt.org/z/4f97hc7dh)可通过编译。

但是如果这个 `requires` 表达式是用作定义 `concept` 的时候，不使用 `typename` 就有不符合预料的结果：

```cpp
#include <iostream>

template<typename T>
concept C = requires{ T::type; };

struct X { using type = int; };

int main(){
    std::cout << std::boolalpha << C<int> << '\n'; // false
    std::cout << std::boolalpha << C<X> << '\n';   // false
}
```

 [测试](https://godbolt.org/z/daq5xdoPW)。
如果我们给*概念*（concept）C 的 `requires` 表达式中的 `T::type` 改成 `typename T::type`，那么运行结果就会变成：`false`、`true`；[测试](https://godbolt.org/z/6W37hdcTa)。

**Comment by Mq-b** [comment]
@frederick-vs-ja

**Comment by AzrBrk** [comment]
会不会是因为 T::type本身就是不对的，
![$@8X4666LBKCIZBP%DGUS40](https://github.com/Mq-b/Modern-Cpp-templates-tutorial/assets/17882266/7a8f0932-70dc-4382-9bcb-9001b8d630a0)

![D22WMCUXIGU QI0QDQ0$2EA](https://github.com/Mq-b/Modern-Cpp-templates-tutorial/assets/17882266/aca53fc2-fdc2-4c82-b8a3-9db6fadf0e07)

 typename T::type才是对的, 图来自cppinsight

**Comment by Mq-b** [comment]
不好说，第一个示例实测了是三个编译器都能通过编译并且得到正确的结果，难道大家都错了？这其实是个扩展？

**Comment by AzrBrk** [comment]
不加typename,编译器不会把type当成类型处理, https://gcc.godbolt.org/z/TGM9fMErr

**Comment by Mq-b** [comment]
问问权威人士，感觉其实有误导别人不加 typename 的嫌疑（

**Comment by Mq-b** [comment]
简单，那第一个用法应该是合理的，它只是普通的 requires 表达式而已，不是类型要求

**Comment by Mq-b** [comment]
不不不，第一个只是要求满足这种形式，是合法表达式即可，而不是类型要求。

**Comment by Mq-b** [comment]
第一个应该算作是“简单要求”。

> 简单要求是任何不以关键词 requires 开始的表达式语句。它断言该表达式是有效的。表达式是不求值的操作数；只检查语言的正确性。

**Comment by AzrBrk** [comment]
https://zh.cppreference.com/w/cpp/language/dependent_name
_在模板（包括别名模版）的声明或定义中，不是当前实例化的成员且取决于某个模板形参的名字不会被认为是类型，除非使用关键词 typename 或它已经被设立为类型名（例如用 typedef 声明或通过用作基类名）_。
所以编译器觉得你是要找一个叫type的成员，没有就false了

**Comment by frederick-vs-ja** [comment]
第一个情况是良构的，只是 requires 表达式求值为 `false`。

达成我们期待的写法应该是 `requires { T::value; }` 和 `requires { typename T::type; }`，但是 `type` 和 `value` 并不是关键词，所以用混了也不会直接导致非良构，只是产生不期待的结果（除非在 `static_assert` 里导致重载决议失败等等）。

**Comment by Mq-b** [comment]
聚聚可以解释一下这个嘛？

> > 任何不以关键词 requires 开始的表达式语句
> 
> 这句话是表达啥？我知道“简单要求”是指啥，但是这句话指啥不知道。

**Comment by Matrix-A** [comment]
> 聚聚可以解释一下这个嘛？
> 
> > > 任何不以关键词 requires 开始的表达式语句
> > 
> > 
> > 这句话是表达啥？我知道“简单要求”是指啥，但是这句话指啥不知道。

就是除了**requires表达式**外的其他表达式

可能是因为直接使用**requires表达式**会导致递归才这样表述的

**Comment by Matrix-A** [comment]
> 聚聚可以解释一下这个嘛？
> 
> > > 任何不以关键词 requires 开始的表达式语句
> > 
> > 
> > 这句话是表达啥？我知道“简单要求”是指啥，但是这句话指啥不知道。

标准文档原文：

A [requirement](https://eel.is/c++draft/expr.prim.req.general#nt:requirement) that starts with a requires token is never interpreted as a [simple-requirement](https://eel.is/c++draft/expr.prim.req.simple#nt:simple-requirement)[.](https://eel.is/c++draft/expr.prim.req.simple#2.sentence-1)
[Note [2](https://eel.is/c++draft/expr.prim.req.simple#note-2): This simplifies distinguishing between a [simple-requirement](https://eel.is/c++draft/expr.prim.req.simple#nt:simple-requirement) and a [nested-requirement](https://eel.is/c++draft/expr.prim.req.nested#nt:nested-requirement)[.](https://eel.is/c++draft/expr.prim.req.simple#2.sentence-2)
— end note]

翻译：

以requires关键词开始的要求永远不会被解释为**简单要求**。
注2： 这简化了**简单要求**和**嵌套要求**之间的区分。 


因吹斯听，又学到了新知识了

**Comment by frederick-vs-ja** [comment]
> > 聚聚可以解释一下这个嘛？
> > > > 任何不以关键词 requires 开始的表达式语句
> > > 
> > > 
> > > 这句话是表达啥？我知道“简单要求”是指啥，但是这句话指啥不知道。
> 
> 标准文档原文：
> 
> A [requirement](https://eel.is/c++draft/expr.prim.req.general#nt:requirement) that starts with a requires token is never interpreted as a [simple-requirement](https://eel.is/c++draft/expr.prim.req.simple#nt:simple-requirement)[.](https://eel.is/c++draft/expr.prim.req.simple#2.sentence-1) [Note [2](https://eel.is/c++draft/expr.prim.req.simple#note-2): This simplifies distinguishing between a [simple-requirement](https://eel.is/c++draft/expr.prim.req.simple#nt:simple-requirement) and a [nested-requirement](https://eel.is/c++draft/expr.prim.req.nested#nt:nested-requirement)[.](https://eel.is/c++draft/expr.prim.req.simple#2.sentence-2) — end note]
> 
> 翻译：
> 
> 以requires关键词开始的要求永远不会被解释为**简单要求**。 注2： 这简化了**简单要求**和**嵌套要求**之间的区分。 
> 
> 因吹斯听，又学到了新知识了，又是美好的一天

这其实是同一个意思。我们需要语文水平好的人把它说得通顺点（英文原文也很绕）。
