### ISSUE TITLE
对形参包展开场所的补充

### ISSUE THREAD

**Issue by Suzukaze7** [Mq-b/Modern-Cpp-templates-tutorial#21]
C++ 只允许在[这几种](https://zh.cppreference.com/w/cpp/language/parameter_pack#.E5.B1.95.E5.BC.80.E5.9C.BA.E6.89.80)语境下进行形参包展开

对于[01函数模板](https://github.com/Mq-b/Modern-Cpp-templates-tutorial/blob/main/md/%E7%AC%AC%E4%B8%80%E9%83%A8%E5%88%86-%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86/01%E5%87%BD%E6%95%B0%E6%A8%A1%E6%9D%BF.md#%E5%8F%AF%E5%8F%98%E5%8F%82%E6%95%B0%E6%A8%A1%E6%9D%BF)使用的几个例子：

- ```cpp
    template<typename...Args>
    void print(const Args&...args){    
        int _[]{ (std::cout << args << ' ' ,0)... };
    }
    ```

    是在**花括号包围的初始化器**中展开

- ```cpp
    template<typename T,std::size_t N, typename...Args>
    void f(const T(&array)[N], Args...index) {
        print(array[index]...);
    }
    ```
    是在**函数形参列表**中展开

所以不能以如下方式通过形参包展开输出所有参数~~而要使用前面那种看起来有点奇怪的方式~~

```cpp
template<typename ...Args>
void print(const Args &...args) {
    (std::cout << args << " ")...;
}
```

**Comment by frederick-vs-ja** [comment]
```cpp
  template<typename...Args>
  void print(const Args&...args){    
      int _[]{ (std::cout << args << ' ' ,0)... };
  }
```

@Mq-b 我在想这个例子是否应该支持空参数列表（`print()`）？目前这个写法在参数列表为空时会导致 `_` 为非良构的 0 长度数组，在严格的模式下造成编译错误。

解决方案是在数组中添加一个元素使其长度始终为正。

```diff
  template<typename...Args>
  void print(const Args&...args){    
-      int _[]{ (std::cout << args << ' ' ,0)... };
+      int _[]{ 0, (std::cout << args << ' ' ,0)... };
  }
```

**Comment by Mq-b** [comment]
@frederick-vs-ja 有道理，唉，要考虑的东西真多（。

**Comment by Mq-b** [comment]
> ```c++
>   template<typename...Args>
>   void print(const Args&...args){    
>       int _[]{ (std::cout << args << ' ' ,0)... };
>   }
> ```
> 
> @Mq-b 我在想这个例子是否应该支持空参数列表（`print()`）？目前这个写法在参数列表为空时会导致 `_` 为非良构的 0 长度数组，在严格的模式下造成编译错误。
> 
> 解决方案是在数组中添加一个元素使其长度始终为正。
> 
> ```diff
>   template<typename...Args>
>   void print(const Args&...args){    
> -      int _[]{ (std::cout << args << ' ' ,0)... };
> +      int _[]{ 0, (std::cout << args << ' ' ,0)... };
>   }
> ```

我又想了一下，我为什么要允许空参（`print()`）调用呢？至少这里完全没必要，不过出于教学目的，可以提及一下。

**Comment by Mq-b** [comment]
> ```diff
>   template<typename...Args>
>   void print(const Args&...args){    
> +      int _[]{ 0, (std::cout << args << ' ' ,0)... };
>   }
> ```

其实我还觉得有点神奇，**`{ 0, (std::cout << args << ' ' ,0)... }`** 如果形参包为空，编译器还会去掉 `0` 后面那个逗号。

**Comment by Mq-b** [comment]
> > 其实我还觉得有点神奇，**`{ 0, (std::cout << args << ' ' ,0)... }`** 如果形参包为空，编译器还会去掉 `0` 后面那个逗号。
> 
> 不需要去掉，花括号初始化器列表一直都允许有一个尾随的逗号。从古代 C++ 起 `int a[] = {0, };` 就是合法的定义。

没用的知识又增加了。
