### ISSUE TITLE
变量模板下示例  x86-gcc13.2编译报错

### ISSUE THREAD

**Issue by ooolize** [Mq-b/Modern-Cpp-templates-tutorial#28]
白老师 看一下这个示例 有什么问题
出处：变量模板-->使用变量模板
https://godbolt.org/z/Yovr6PvE5

**Comment by Mq-b** [comment]
你是否把 issue 当成了提问的地方了。
文档不写在函数作用域只是为了简洁，懒得创建个函数，但不代表你可以这样。

**Comment by Mq-b** [comment]
而且你全局作用域写个 `v<int>;` 有什么用处。

```cpp
template <typename T>
constexpr T v{};

int b = v<int>;

int main(){}
```

还算正常点。

**Comment by ooolize** [comment]
奥奥 好的 抱歉

**Comment by Mq-b** [comment]
文档写的是：

```cpp
template<typename T>
constexpr T v{};

v<int>;     // 相当于 constexpr int v = 0;
```

这已经很简洁了，表示的意思，你关注点太奇怪了，要是非要我写个函数里面再写 `v<int>` 那也太....

**Comment by Mq-b** [comment]
至于你说的那个报错，的确是有一些问题的，只是通常不会那样去写（因为毫无意义），所以希望你别太在意。
