### ISSUE TITLE
函数模板那一节如何使用简单的语言解释一下为什么模板不能分文件 `.h` `.cpp`

### ISSUE THREAD

**Issue by Mq-b** [Mq-b/Modern-Cpp-templates-tutorial#4]
倒也不是真不能分，但是会很麻烦，如何用比较简单的语言稍微聊一下。

因为感觉单独的说一句：模板不能分文件。很突兀，其他原因又挺麻烦的。

**Comment by luuuua** [comment]
白老师好，这句话我看了10s才看懂。
因为感觉简单的一句”模板不能分文件“很突兀，其他原因又挺麻烦的
是这么理解吗🤣

**Comment by Mq-b** [comment]
> 白老师好，这句话我看了10s才看懂。 因为感觉简单的一句”模板不能分文件“很突兀，其他原因又挺麻烦的 是这么理解吗🤣

阿巴巴，差不多吧。
